services:
  # 1. PostgreSQL - 1 Server, 2 Databases
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - thapcam_e-commerce

  # 2. Redis - Cache cho Giỏ hàng
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: always
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - thapcam_e-commerce

  # 3. RabbitMQ - Message Broker 
  rabbitmq:
    image: rabbitmq:3-management-alpine 
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${DOCKER_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${DOCKER_RABBITMQ_PASSWORD}
    ports:
      - "${DOCKER_RABBITMQ_PORT}:5672"  
      - "${DOCKER_RABBITMQ_UI_PORT}:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - thapcam_e-commerce  

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  thapcam_e-commerce: 
    driver: bridge